version: '3.8'

services:
  backend:
    build:
      context: ./movies-collection-backend # Path to your backend Dockerfile directory
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./movies-collection-frontend # Path to your frontend Dockerfile directory
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
