apiVersion: v1
data:
  APP_SECRET: SomeSecret
  MONGO_URI: mongodb+srv://singhvikramsingh06:LHDbulftW3XDv027@movies.xx75x.mongodb.net/?retryWrites=true&w=majority&appName=movies
  PORT: "5000"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend-env
  name: backend-env
